### ISSUE TITLE
EPIC - IF Website Revamp

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#1024]
**Why**: The IF website struggles to engage visitors and inspire them to contribute to the IF initiative.
**What**: Optimise the IF website to cater for the OS maintainers who care about sustainability to wow them in 5 Minutes, e.g. 

All discussions in this [gdoc](https://docs.google.com/document/d/1HlFyQVfoLu6kuC1ZsQQNJmQW8GiJULuHfM1Zgs4wp4w/edit).

**Tasks**

### Blog
- [ ] Menu item Blog to take to docusaurus blog
- [ ] Get some change logs into the blog to begin with
- [ ] Case Studies

### Landing page 
- [ ] #879
- [ ] #1000
- [ ] #1002
- [ ] Design new layout

**Comment by tholewis** [comment]
Wanted to follow up on the Epic. Has there been any work done on this issue or is it on the backlog for now? I'm asking because I wanted to include IF in a workshop I am building and didn't want to work on that section currently if the website will be changing soon. Also, a "five minute to wow!" video on the homepage sounds like a good idea! Just wanted to see where this was at.

**Comment by zanete** [comment]
@jawache @jmcook1186 FYI there is a question above I'm not able to answer, so tagging you! 🙏

**Comment by jmcook1186** [comment]
@tholewis @zanete 
afaik IF website revamp is backlogged. 
There is an IF training course being developed, now led by @jawache that might be useful though.
