### ISSUE TITLE
EPIC - Manifest Visualiser 2

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#1028]
**Why**: Sub of #1025
**What**: Add helpful features to the visualiser, continuation from #951 

## Tasks
- [x] #1060
- [x] #1058
- [x] Deploy visualiser on the IF website
- [x] Implement GA in visualiser to measure views

### Landing page
- [ ] Copy for the Visualiser landing page

**Comment by zanete** [comment]
@jawache please add your notes here 🙏 (unless you have created another issue in which case I'll merge)

**Comment by jawache** [comment]
@zanete / @osamajandali / @jmcook1186 I've put my thoughts above and in sub-tickets, please comment and ajust/suggest.
