### ISSUE TITLE
EPIC - IF Graduation

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#1029]
**Why**: Sub of #1025 
**What**: Any procedural tasks we need to do to get the project graduated according to GSF project graduation criteria

**Scope of work:**
 - [x] #1074
 - [x] @manushak Do a quick audit to identify remaining tasks that are not already listed below
 - [x] @manushak updated the project overview (README)
 - [x] @manushak updated how to contribute ([contributing.md](http://contributing.md/))
 - [x] @manushak Ensure we have unit test coverage
 - [x] @manushak Add an enablement.md file that introduces and takes people to the if docs website
 - [x] @jmcook1186 Get a case study from a contributor about its adoption ([adopters.md](http://adopters.md/))
 - [x] @narekhovhannisyan find out what it means - how it meets 100% of the applicable criteria for the Open SSF Best Practice Badge ([security.md](http://security.md/))
 - [x] @narekhovhannisyan add a code checker Code QL (as per https://www.bestpractices.dev/en/criteria/0)
 - [x] Add OKRs to the repo
 - [x] Attach 1.0 v release tag
 - [x] Propose graduation to OS working group via issue template
 - [ ] Communicate the graduation externally

--- 
Excerpt from [graduation process](https://www.notion.so/grnsft/Software-Project-Lifecycle-706d000efe934dddbcae372f6eceaa21?pvs=4#819c2437fc464c9a8f1a537f76243253):
In addition to the criteria from the previous stage, **the project must have:** 

- An active set of contributing members from at least two member organizations
- A public GitHub repo with clear project documentation that sets out:
    - the project overview (README)
    - how to contribute ([contributing.md](http://contributing.md/))
    - end-user guide ([enablement.md](http://enablement.md/))
    - test coverage
    - how it fits within GSF Theory of Change
    - evidence of utility through real world use cases in the production environment, including testimonials ([adopters.md](http://adopters.md/))
    - how it meets 100% of the applicable criteria for the Open SSF Best Practice Badge ([security.md](http://security.md/))
- Made a release deployment, even if this is a ‘developer preview’
- An incident process agreed with GSF PM
- GSF processes set up including:
    - a project team mailing list
    - regular project meetings
    - the provision of regular updates to the Working Group
    - defined OKRs agreed by the assigned GSF PM

**Comment by zanete** [comment]
@narekhovhannisyan & @manushak FYI this is coming - it would be good to get an audit of what we already have vs what's necessary so we can divide and conquer

**Comment by zanete** [comment]
q: bug triage frequency - change the text from weekly to ad-hoc

**Comment by manushak** [comment]
@zanete I reviewed the Notion documentation regarding the Graduation part and all the key points are already in this task

**Comment by narekhovhannisyan** [comment]
research on Best Practices
website: https://www.bestpractices.dev/en
criterias: https://www.bestpractices.dev/en/criteria/0
github repo: https://github.com/coreinfrastructure/best-practices-badge

**Comment by zanete** [comment]
* @manushak to provide a PR for unit tests today
* @manushak to add enablement.md right after that
* @jmcook1186 to prepare the adopters
* @jmcook1186 to address the comments on security.md PR

**Comment by manushak** [comment]
PR for enablement.md: https://github.com/Green-Software-Foundation/if/pull/1087

**Comment by jmcook1186** [comment]
Status update 5/12/24 @zanete 

I believe we are pretty much there with all the graduation requirements except the user testimonials - I've reached out to a few people and put a general call out on the IF mailing list but no-one has provided anything yet.

To tick everything off the graduation checklist, we need to merge 1084, 1085, 1087, 1088 and release v1.0, plus add the user testimonial when we get one. Maybe we need @jawache to lean on some of our users to get this done!

**Comment by zanete** [comment]
@jmcook1186 to discuss with @jawache how to get IF to the steering committee.

**Comment by jmcook1186** [comment]
Raising a motion to graduate IF by tomorrow, for consideration over next 2 weeks by SC
@zanete @narekhovhannisyan @manushak

**Comment by narekhovhannisyan** [comment]
@jmcook1186 ok let's start that phase by tomorrow, other fixes we will provide retroactively

**Comment by zanete** [comment]
Awaiting a response from the official Project Leads

**Comment by jmcook1186** [comment]
Closing as complete
