### ISSUE TITLE
BETA (CarbonHack) Milestone Tracker

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#311]
Issue for tracking IF development targets for Carbon hack.
Deadline: **26th February**

## Hackathon
- [x] Agree on prize judging criteria [issue](https://github.com/Green-Software-Foundation/if/issues/345)
- [x] Weekly link to IF office-hours (on the hackathon board) [issue](https://github.com/Green-Software-Foundation/if/issues/346)
- [ ] "broken/dream" impls for hackers to fix available in IF examples/impls directory: [issue] ABANDONED (https://github.com/Green-Software-Foundation/if/issues/317)
- [x] Carbon Hack issues board is populated with project ideas: [issue](https://github.com/Green-Software-Foundation/hack/issues)

## Documentation
- [x] Video tutorials available in docs for: [issue](https://github.com/Green-Software-Foundation/if/issues/299) ABANDONED in favour of weekly livestreams
    - [x] installing and running IF 
    - [x] writing an impl [issue](https://github.com/Green-Software-Foundation/if/issues/338)
    - [x] creating a model [issue](https://github.com/Green-Software-Foundation/if/issues/339)
    - [x] model building best practices guide [issue](https://github.com/Green-Software-Foundation/if/issues/361)

- [x] Documentation is up to date and comprehensive
    - [x] website docs are up to date: [issue](https://github.com/Green-Software-Foundation/if/issues/335)
    - [x] all necessary disclaimers are in place: [issue](https://github.com/Green-Software-Foundation/if/issues/302)
    - [x] model READMEs are up to date and complete: [issue](https://github.com/Green-Software-Foundation/if/issues/335)
    - [x] Shell model spec: [issue](https://github.com/Green-Software-Foundation/if/issues/336)
    - [ ] Documenting exceptions and error debugging guide: [issue](https://github.com/Green-Software-Foundation/if/issues/337) - bumped to QA epic
- [x] Visualization documentations (use of Graphana): [issue](https://github.com/Green-Software-Foundation/if/issues/334)

## Features

- [x] There are example impls available in the IF repo demonstrating all core IF features
- [x] Implement solution for `units.yaml` strictness in IF repo
- [x] Update model signature [issue](https://github.com/Green-Software-Foundation/if/issues/355)
- [x] Add groupby feature [issue](https://github.com/Green-Software-Foundation/if/issues/385)
- [x] Release and code freeze of IF and models shortly before hackathon starts
- [ ] Exceptions point people towards YAML line hint: [issue](https://github.com/Green-Software-Foundation/if/issues/287) BUMPED to QA epic
- [x] Debugging functionality is up to spec: [issue](https://github.com/Green-Software-Foundation/if/issues/181)
- [x] Time normalization feature is fully implemented: [issue](https://github.com/Green-Software-Foundation/if/issues/286)
- [x] Aggregation feature fully implemented: [issue](https://github.com/Green-Software-Foundation/if/issues/320), [issue](https://github.com/Green-Software-Foundation/if/issues/296)
- [x] Component sub grouping feature fully implemented:  [issue](#331) 
- [x] MockImporter that generates dummy data based on configured params to help design other models: [issue](https://github.com/Green-Software-Foundation/if/issues/332)
- [ ] Ability to function with relative times as well as static times, e.g. all data before now in the last 30 mins: [issue] ABANDONED (https://github.com/Green-Software-Foundation/if/issues/333)
- [x] IF is sufficiently performant to run graphs with 100s - 1000s of nodes: [issue](https://github.com/Green-Software-Foundation/if/issues/300)
- [x] IF has a native CSV exporter: [issue](https://github.com/Green-Software-Foundation/if/issues/298)

**Comment by jmcook1186** [comment]
Urgent task for Sprint 4 is to discuss changing thew model signature with @jawache - if this is a necessary upgrade then we should start planning in detail this sprint and implementing next sprint.

**Comment by jmcook1186** [comment]
Closing as complete
