### ISSUE TITLE
Document the list of exceptions we accept from plugins and the expected behaviour when raising that exception.

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#337]
Sub of #655 

**What**
This issue covers documenting the list of exceptions we accept from plugins and the expected behaviour when raising that exception.

**Why**

For users, having reference documentation that lists out all of the possible errors that can be thrown by a plugin or by the IF will help them understand why their IF run failed. Developers will be able to create plugins that expose the same errors and ensure they behave in the accepted way, providing a better overall user experience if the set of possible exceptions are clear. Having a list of possible exceptions also enables us to ensure we cover all of the possible failure modes in our testing, or at least to see track our coverage.

**Context**
We are defining a set of exceptions that can be thrown by a plugin or by the framework itself and asserting the precise behaviours that cause those errors to be thrown. This enables plugin developers to conform to our expectations and provide a better experience for users by using well known errors. To really provide these benefits, we need accessible documentation that enumerates the exceptions and explains the behaviours that cause the exceptions to be thrown.

**Acceptance criteria**
- [x] if.greensoftware.foundation contains a list of every exception that can be thrown by IF with a description of the conditions that cause the exception to be thrown and (briefly) how to remedy it.
  - We can start a new page for this under `Reference/exceptions`
- [x] A short written description exists on the `Reference/exceptions` page explaining at a high level how errors are handled in the plugins we maintain (there will be a follow-up task to standardize and document the errors arising from plugins after the migration to `builtins` - right now they are a bit too disparate to document well)

**Statement of work**
- [x] Step 1: audit current IF and plugin source code and list out all the exceptions that can be thrown TODAY
- [x] Step 2: Create page on if.greensoftware.foundation (at `reference/exceptions`) that includes every exception with a description of the behaviour that causes it to be thrown and a suggested remedy.

**Blocks**
- #600

**Comment by jmcook1186** [comment]
included in Sprint 5, but as stretch goal

**Comment by dcrreynolds** [comment]
I would like to second this. I'm interested in the hackathon but new to typescript. Without docs on how to get this running in a debugger progress is slow.

**Comment by jmcook1186** [comment]
@zanete I down-scoped this issue to cover only documenting our current exceptions on if.greensoftware.foundation and identifying gaps - added acceptance criteria and SoW and consider it ready to go.

This is important preparatory work for identifying how to improve how users can diagnose issues with IF, e.g. #600 
We need this done in advance of a call about diagnosing issues which we should schedule for when @jawache is fully back online.

**Comment by zanete** [comment]
Capturing status in the standup: - currently listing the errors in the IF, haven't started the plugins yet, and will not include messages that are generated by the external libraries

**Comment by zanete** [comment]
Decision made to break this task in two parts:
1 - IF 
2 - builtin plugins
1st part is doable now and will be finalised, 2nd will be taken into a separate issue and done after all plugins moved to if/builtins

**Comment by narekhovhannisyan** [comment]
## IF framework errors

| Error class                     | Messages                                                                |
| ------------------------------- | ----------------------------------------------------------------------- |
| `CliInputError`                 | Output path is required.                                                |
|                                 | CSV export criteria is not found in output path.                        |
|                                 | Please append it after --output <path>#.                                |
|                                 | ts-command-line-args lib error messages                                 |
| `ManifestValidationError`       | Generated by ZOD framework                                              |
| `ModuleInitializationError`     | Provided module: '${path}' is invalid or not found.                     |
|                                 | Invalid exhaust plugin: ${pluginName}.                                  |
| `InvalidAggregationParamsError` | Aggregation is not possible for given ${metric} since method is 'none'. |
|                                 | Aggregation metric ${metric} is not found in inputs[${index}].          |
| `InvalidGroupingError`          | Invalid group ${type}.                                                  |
| `PluginCredentialError`         | Initalization param 'method' is missing.                                |
|                                 | Initalization param 'path' is missing.                                  |
| `PluginInitalizationError`      | Not initalized plugin: ${name}.                                         |
|                                 | Check if ${name} is in 'manifest.initalize.plugins'.                    |
| `WriteFileError`                | Failed to write CSV to ${outputPath}: ${error}                          |

## Plugin errors

Unofficial plugins

```js
'AuthorizationError',
'APIRequestError',
'InputValidationError',
'UnsupportedValueError',
'ConfigValidationError',
```

Official plugins

```js
'InputValidationError',
'UnsupportedValueError',
'ReadFileError',
'WriteFileError',
'MakeDirectoryError',
'ConfigValidationError',
```

**Comment by zanete** [comment]
@jmcook1186 do we have an issue that covers the exceptions for the plugins? is so, please link here 🙏

**Comment by jmcook1186** [comment]
@zanete yes its here https://github.com/Green-Software-Foundation/if/issues/700

**Comment by jmcook1186** [comment]
PR to update documentation here https://github.com/Green-Software-Foundation/if-docs/pull/71
