### ISSUE TITLE
Reach out to orgs to take responsibility for plugins

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#546]
Sub of #656 

**what**

Reach out to organizations that could take ownership of specific plugins in our `if-plugins` and `if-unofficial-plugins` repositories to support later external migration of the plugins.

**rationale**

We want to gradually deprecate the `if-unofficial-plugins` repository by passing responsibility for specific plugins to the orgs best positioned to maintain them. The first step is to identify and then reach out to those orgs.

**acceptance criteria**

- [x] Real Time Cloud have been approached to take ownership of `cloud-metadata` from `if-plugins`
	- Discussion on this has started already, [here](https://github.com/Green-Software-Foundation/if-plugins/issues/83)
- [ ] `teads-curve` removed from `if-unofficial-plugins` and replaced with generics pipeline
- [x] Bloomberg (?) to take on `grafana-exporter`
- [x] Microsoft have been approached to take ownership of `azure-importer` from `if-unofficial-plugins`
- [x] Boavizta have been approached to take ownership of `boavizta` from `if-unofficial-plugins`
- [x] Green web foundation have been approached to take ownership of CO2js from `if-unofficial-plugins`
- [x] Watt-time have been approached to take ownership of `watt-time` from `if-unofficial-plugins`
- [x] Thoughtworks have been approached to take ownership of `ccf`
- [ ] `tdp-finder` csvs move to its own repo

**Implementation details**

@jawache to instigate majority of these conversations as he has open dialogues with many of the target organizations already.

**Comment by zanete** [comment]
@jawache when could you realistically start this? 🙏

**Comment by zanete** [comment]
@jawache do you feel up for this one this week or should we move to next? There is a strong desire to launch the plugin registry with most of the plugins cleaned up and ownership clarified 🙏 
cc @jmcook1186

**Comment by jawache** [comment]
@jmcook1186 and @zanete so I think realistically this will have to be me perhaps making introductions but then @jmcook1186 following up.

I'd suggest we set up a 1hr working call next week where we just go through these, craft some emails together and send out, @jmcook1186 wanna try and find some time next Thursday?

**Comment by jmcook1186** [comment]
yes - fantastic. I'll suggest a time.

**Comment by zanete** [comment]
great, thanks both! I will leave it to you to organise (and moving this to next week so it doesn't mess with with the board)

**Comment by zanete** [comment]
@jawache how's this going? who have you contacted and what's new?

**Comment by jawache** [comment]
Emails all sent @zanete

**Comment by jmcook1186** [comment]
all third parties have been contacted
