### ISSUE TITLE
Add labels for `needs-triage`, `fix-now`, `fix-later` and `won't-fix` to Github repositories

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#589]
Sub of #651 

**What**

Add labels for needs-triage, fix-now, fix-later and won't-fix to Github repositories

**Why**

As a core dev I want an easy way to tag bugs with their post-triage status. As a user, I want to quickly and clearly see the status of active bug reports. This improves our internal process for tracking bugs because we can see at a glance what was the outcome from a bug triage and whether a bug requires attention. It also improves our public facing communications because users can quickly tell whether a bug is being worked on, scheduled to be worked on, or whether they should not expect any action to be taken.

**Context**

We can apply three simple labels signalling the status of a bug report after it has been triaged: `fix-now` for urgent bugs, `fix-later` for non-urgent bugs, and `wont-fix` for bug reports that we will not work on because it is benign, or the report is somehow incorrect.

**Prerequisites**
None

**Statement of Work**

- [x] add four new labels to all IF repositories (`if`, `if-plugins`, `if-unofficial-plugins`, `if-plugin-template`)
- [x] update bug report documentation to include label definitions

**Acceptance Criteria**
- [x] labels `needs-triage`, `fix now`, `fix-later` and `wont-fix` are added to `if`, `if-plugins`, `if-unofficial-plugins` and `if-plugin-template` repositories
- [x] Bug report documentation describes the new labels and their intended usage

**Reviewer**
@manushak

**Comment by jmcook1186** [comment]
@zanete - labels added for all repositories via the `gh` CLI (no PR)
documentation updated in https://github.com/Green-Software-Foundation/if/pull/663
