### ISSUE TITLE
Write new docs for debugging IF

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#601]
Sub of #655 

## User Story
As a developer I want to be able to look up the meaning and suggested remediations associated with the IF logs and error messages. This will help me to develop quickly using IF.

## Rationale
We will be refining our logging protocol in issue #600 and our error messages in #593 so we should also take the opportunity to document these changes comprehensively for our users. This should include:
- reference documentation for all error messages
- reference docs for logs
- user guide for remediating common errors

## Implementation details

- [ ] write error message reference page for if.greensoftware.foundation
- [ ] write logging reference page for if.greensoftware.foundation
- [ ] write user tutorial for remediating common errors for if.greensoftware.foundation

## Priority
3/5

## Size
L

## What does "done" look like?
Three new pages exist on if.greensoftware.foudnation

## Deadline
tbc

**Comment by jmcook1186** [comment]
Closing as captured in #593 and #602
