### ISSUE TITLE
Define process for integration/regression testing

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#605]
## User story
As a core developer I want to make sure my changes don't break anything before making releases.

## Rationale
We want to incorporate a new strategy for integration testing and regression testing based around manifest files that will require several discussions within the team and documentation before being fully implemented. This ticket covers the defining of the strategy and is expected to spawn more tickets for the implementation.

## Implementation details
- [ ] create a proposal for a process and the required tooling
- [ ] organize at least one spike call with core team to refine and confirm
- [ ] write up documentation explaining testing procedures

## Priority
5/5

## Size
L

## What does "done" look like?
Team have agreed a process, documentation exists

## Does this require updates to documentation or other materials??
Yes, internal process documentation

## Deadline
tbc

**Comment by jawache** [comment]
@jmcook1186 similar point to the other QA ticket, I believe this ticket is redundant and all this will be resolved by the #615 ticket.

- Regression tests will be a folder of manifest files that contain manifests that previously triggered a bug that we fixed.
- Integration tests will be a folder of manifest files that contain many different plugins in a pipeline so we test they all "integrate" together.

**Comment by jmcook1186** [comment]
ok, agree, closing as redundant
