### ISSUE TITLE
Define process for documenting test cases

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#610]
## User story

As a core developer I want to know what positive and negative test cases exist when i am writing or updating our source code.

## Rationale

We are implementing more integration and regression tests into our QA protocols. These should be documented in a human readable and auditable way, so that we can understand our test coverage easily.

## Implementation details
- [ ] create proposal for documenting test cases
- [ ] create proposal for test case maintenance/update process
- [ ] discuss with team and get sign-off
- [ ] implement for current test cases

## Priority
4/5

## Size

M

## What does "done" look like?
Test cases are documented, process is documented

## Deadline
tbc

**Comment by jawache** [comment]
@jmcook1186 again I think this one is covered by #615 (unless we are talking about unit tests?) the SoW here translates to the SoW for how we maintain a folder of manifest files that act as our test cases.

Makes sense to me to close this one and I'll merge the SoW for all of the other tickets in the the main one about creating a folder of manifest files that we use for testing.

**Comment by jmcook1186** [comment]
Agree, closing as superseded by #615
