### ISSUE TITLE
Define process for ensuring docs and code stay in sync

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#611]
## User story
As a user, I want to be able to read documentation and be confident it applies to the latest stable version of IF.

## Rationale
There have been several cases where documentation changes have been missed when the code has changed, and this has caused the documentation to fall out of sync with the source code. This has been picked up by user feedback faster than it has been picked up by the core team on several occasions. To avoid this, we need to implement a process to keep the documentation and the source code in sync.

## Implementation details
- [ ] create process proposal
- [ ] discuss with core team
- [ ] implement, spawning additional tickets if necessary

## Priority
4/5

## Size
S

## What does "done" look like?
Process implemented

## Deadline
tbc

**Comment by jawache** [comment]
@jmcook1186 I would merge this with #613 (which I've proposed we broaden our to document our process), the same goes for testing, an issue is not ready to be worked on unless any and all testing requirements have been added to the acceptance criteria and SoW and any and all documentation requirements have beed added to the acceptance criteria and SoW for any issue.

It should just be part of the refinement processes, we can put reminders in the issue template or other nudges or ceremonies if it's not working, but makes sense to discuss this all on that one ticket so we don't have to jump around different tickets to have a conversation about refinement.

**Comment by jmcook1186** [comment]
ok, closing as redundant
