### ISSUE TITLE
Migrate plugins from `if-plugins` to `if` as builtins

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#616]
Sub of: #656 

## User story
As a user I want to have minimal dependencies and packages to manage to use IF. 

## Rationale
We currently maintain multiple repositories for plugins. However, for the core standard library of plugins we could move these inside the IF repository and use them as "builtins" instead of plugins. This would ease the overall project maintenance, reduce the packages we have to maintain and make the set of `if` repositories easier to navigate.

## Implementation details
- [ ] identify the plugins we want to migrate
- [ ] evaluate whether any plugins from if-unofficial-plugins should become builtins
- [ ] migrate code into builtins as appropriate
- [ ] determine whether we want to maintain anything in if-plugins - if not, deprecate and remove repo
- [ ] test and QA
- [ ] update documentation

## Priority
4/5

## Size
L

## What does "done" look like?
tbc

## Does this require updates to documentation or other materials??
documentation will require updates, including both plugin readmes and website documentation.

## Deadline
tbc

**Comment by jmcook1186** [comment]
We have individual tickets for each plugin being migrated, so maybe this can be closed out?

**Comment by zanete** [comment]
Covered by 
#678 
#661  
#676  
#677 
#678 
#679 
#680  
#681  
#682 
#683
