### ISSUE TITLE
Add negative flow manifests to test scenarios

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#619]
## User story
As a core developer I want to be confident my changes haven't broken any expected behaviours in IF. 

## Rationale
We currently only have the ability to test positive flows through IF. After implementing logging to file, we can create negative test scenarios too, to check that IF error out in the expected ways when it is supposed to.

## Implementation details
- [ ] enumerate the ways that IF is supposed to error out
- [ ] design test cases for each intended failure mode and write up as manifests
- [ ] add documentation for the test cases in human readable format so we can quickly assess coverage

## Priority
3/5

## Size
L

## What does "done" look like?
Negative test cases exist, behave in expected way, and are documented

## Does this require updates to documentation or other materials??
Yes, test cases require documentation

## Deadline
tbc

**Comment by jawache** [comment]
Hi @jmcook1186 I believe this ticket is now redundant, covered by #615 and #592. I have nothing to add to the acceptance criteria that isn't already covered in the above two tickets, suggest closing.
