### ISSUE TITLE
Define and implement automated testing protocol

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#620]
## User story
As a developer I want to be able to quickly confirm that my changes do not break any intended behaviours of the IF. I want to do this with the minimum of manual work.

## Rationale
We want as much of our testing to be automated as possible so that anyone can perform the necessary tests and that we can be confident int he changes we are pushing without having to do lots of manual work. This includes unit tests, integration and regression tests.

## Implementation details
- [ ] QA to propose process
- [ ] team to spike on refining process and coming to agreement
- [ ] document new processes such that they are useable and maintainable by anyone
- [ ] implement automated tests

## Priority
4/5

## Size
L

## What does "done" look like?
Automated testing is implemented and documented

## Deadline
tbc

**Comment by jawache** [comment]
@jmcook1186 I'm not sure what an automated testing protocol is over and above what's defined in #615, if there isn't anything else i'd close this ticket, if there is please can we provide more information. I'm finding it challenging to refine this and define acceptance criteria.

**Comment by jmcook1186** [comment]
Closing as superseded by #615
