### ISSUE TITLE
Design `if-env` command line tool

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#624]
## User story
As a user I want to be able to quickly create an environment to run my manifests, taking all my plugins into account.

## Rationale
We can provide a command line tool that will inspect the package.jsons of the if and all the plugins listed in a manifest and create a unified package.json that can be used to define the environment in which the manifest can run. This will make it easy for users to run manifests and will also be useful scaffolding for our sandboxes, playgrounds and scenario testing. This ticket covers the design and specification but not the actual building of the tool.

## Implementation details
- [ ] create a design proposal for the `if-diff` tool
- [ ] share with the team for approval
- [ ] create documentation and specification
- [ ] create new ticket for the actual build

## Priority
3/5

## Size
L

## What does "done" look like?

Approved specification document exists, sufficient to build from.

## Deadline
tbc

**Comment by zanete** [comment]
Proposing to include the design phase in the workflow of https://github.com/Green-Software-Foundation/if/issues/636, closing to remove noise
