### ISSUE TITLE
Design `if-verify` command line tool

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#625]
## User story

As a user I want to be able to re-execute a manifest and verify that the outputs are correctly reported.  This is important for the transparency and integrity of manifests.

## Rationale
We want impact assessments to be verifiable. We can make verification easy by providing a command line tool that will take an output file as an argument, replicate the environment and context defined in the file, re-execute it, and return a boolean true/false showing whether the generated outputs are identical to the one passed to the cli tool.

## Implementation details
- [ ] create a design proposal document for the `if-verify` tool
- [ ] share design proposal with the team to approve or refine
- [ ] if approved, write up design as a specification that can be used to guide the build
- [ ] create new ticket for the actual build

## Priority
3/5

## Size
M

## What does "done" look like?
Design spec exists and is approved by team

## Deadline
tbc

**Comment by zanete** [comment]
proposing to include the design of this as part of the workflow of https://github.com/Green-Software-Foundation/if/issues/638 and closing to remove noise
