### ISSUE TITLE
Design `if-blitz` command line tool

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#627]
## User story
As a user I want to be able to quickly test out IF in a sandbox environment. When I raise bug reports I ant to be ablke to link to an online sandbox so devs can instantly repro.

## Rationale
A command line tool that will take a user's current environment and instantly replicate it in an online sandbox that can be shared with devs. This will help people to accurately report bugs, experiment with things in a safe environment, etc.

## Implementation details
- [ ] create a design document for the tool
- [ ] share design doc with team for refinement and approval
- [ ] create new ticket for building tool

## Priority
3/5

## Size
L

## What does "done" look like?
design doc is approved by team

## Does this require updates to documentation or other materials??
no

## Deadline
tbc

**Comment by jawache** [comment]
Hey @jmcook1186 can we approach these tickets differently? It's not clear to me what a design doc is and how we are going to get clear on requirements are taken into account? At this stage we just need to make clear what the purpose of this tool is, the cli arguments and expected inputs/outputs and thinking about it that aligns to defining the acceptance criteria of the "build tool" version of the ticket.

The design tickets should be the refinement for the build tickets and specifically fleshing out the acceptance criteria section. My acceptance criteria for this tool would detail the CLI params, expected behaviour for each param, sample inputs and outputs. That's enough "design", I trust the team to build the right solution based on a clear acceptance criteria like that.

**Comment by zanete** [comment]
Proposing to include the design phase as part of the workflow of https://github.com/Green-Software-Foundation/if/issues/639 and closing to remove noise
