### ISSUE TITLE
Create public google group for if contributors

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#628]
Sub of #657 

**What**: Create a public google group where non-members and members can discuss impact framework
**Why**: We want to create a space for contributors to have discussions with us and between each other that doesn't add noise to the issue and PR boards
**Story**: As a user I want a place to give feedback and open discussions about IF that aren't appropriate for the issue/pr board.

**SoW**

- [x] create google group if-community@greensoftware.foundation
- [x] determine and document the purpose of the group and the expected topics and behaviours
    - this will include adding a brief pointer on the IF readme and the contribution guidelines page on if-docs
- [x] announce on repo readmes, on if weekly call and to hackathon email list. 

**Acceptance Criteria**
- [x] A public google group for IF exists
    - GIVEN: a public google group has been created
    - WHEN: a user wants to participate
    - THEN: they should be able to sign up and participate in discussions on the email thread

- [x] Documentation exists that directs users to the google group
    - GIVEN: a user has found their way to the IF website or github repository and they want to start participating
    - WHEN: they read our project README and contribution guidelines they find infomation about our google group and guidance for how to engage there
    - THEN: they will be directed to the appropriate group and have clear expectations for what they can do there

- [x] The google group has been tested using a dummy account owned by a core team member
    - GIVEN the google group exists
    - WHEN a core team member joins using a dummy account and observed that the onboarding flow works as expected
    - THEN we can roll out to the public confident that they will be able to onboard successfully

- [x] the core team has discussed and documented the ways the google group should be used (what kinds of discussions do we want to have there, what are the boundaries, what permissions should be imposed)
    - GIVEN the google group exists
    - WHEN the team want to start, respond to or moderate a public discussion
    - THEN the knowledge as to how and when to do this is accessible to the team and also publicly visible (likely as part of the contribution guidelines)
