### ISSUE TITLE
Document the QA requirements for merging into main/release branches

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#632]
Sub of : #651 

**What**

Define the QA requirements for merging code into each of `main` and `release` branches. Add clear documentation to the `if` repository and the if.greensoftware.foundation docs website to explain the requirements.

**Why**
As a core developer I want a clear process for deciding when to merge code into each branch and when/how to cut releases so that I can minimize the cognitive load associated with these tasks and provide a consistent experience for our users and contributors.

**Context**

We recently refined our Githiub processes during the `if` refactor, including writing down rules for merging onto `main` and `release` in each of our repositories here: https://github.com/Green-Software-Foundation/if/blob/main/github-processes.md. 

However, the QA epic prep provided an opportunity for more detailed introspection on this topic, and the documentation now needs reviewing and possibly refining again. In particular, we want to make sure we are optimizing the balance between developer agility and the quality of the product we are publishing. We don't want to publish buggy code but we also don't want to be overburdened with QA to an extent that we are too slow to ship new features.

We need to ensure that the `release` branch is always reliable, stable and contains only high quality code that we are very confident in. The `main` branch can be a little more relaxed as it is where we push the latest updates that accelerate beyond what is in `release`. This means there can be slightly different QA requirements across the two branches, and a defined process for merging one branch into another.

For the dev branch we should focus on automated tests as much as possible to keep the pace of development high. As a small dev team with only one dedicated QA person, we have to accept that bugs will occasionally creep into `main`. However, we should ensure a strict process minimizes their chances of propagating into `release`.

Our discussions have yielded the following guidelines:

- prioritize automation on `main`, avoiding manual testing wherever possible. 
- encourage community to help fix bugs we have identified on `main`
- manual testing should focus on the `release` branch, as this is where it is most important to catch edge cases and ensure things behave in the intended way.
- releases do not have to be entirely bug-free. We can release with small, non-critical bugs and encourage community contributors to help us fix them in time for the next release. This can maintain shipping velocity and provide onboarding opportunities.

**Prerequisites**

No particular prerequisites, but there are useful notes on this topic in our internal notion and the existing GH processes doc here: https://github.com/Green-Software-Foundation/if/blob/main/github-processes.md

**Statement of work**

- [x] PR to update the existing guidelines [here](https://github.com/Green-Software-Foundation/if/blob/main/github-processes.md) to document our new process (as described above)
- [ ] PR to link out to our process doc from `contributing.md` 
- [ ] PR to link out to our process doc from contributions page on if.greensoftware.foundation.

**Acceptance criteria**

- [x] [Current process doc](https://github.com/Green-Software-Foundation/if/blob/main/github-processes.md) updated, and new content added and any obsolete content removed.
- [ ] Contributions page on if.greensoftware.foundation includes sumamry of branch merging rules and link to our updated Github processes [documentation](https://github.com/Green-Software-Foundation/if/blob/main/github-processes.md)

**Deadline**
tbc

**Comment by jawache** [comment]
@jmcook1186 I agree with all your points in the Context section above. I've adjusted the SoW to be just updating the docs and moved some of those points to the acceptance criteria since it made more sense there.

The exact process will be a PR is created to update the docs with the new process and we'll have the opportunity to discuss there, there isn't a need for a spike on this since we've discussed extensively in the Notion docs and you've summarized all the important points already in the context above. I'd suggest just go ahead and update the docs and the PR is the point at which the team can weigh in, but we've discussed this pretty extensively already in the document.

FYI I think it makes sense for you to take on this (and other "process" document updates) the relevant team members can weigh in on the PR that's created and add their comments there.

**Comment by jmcook1186** [comment]
@jawache ok updated and reassigned, awaiting approval

**Comment by jawache** [comment]
Given it my thumbs up, fyi SoW should always be check boxes so we can tick off when completed and see how much work is left on a ticket.

**Comment by zanete** [comment]
Blocked until #650 epic is implemented (at least this one #621)

**Comment by zanete** [comment]
This could be worked on without disclosing all the details

**Comment by zanete** [comment]
According to @jmcook1186 the work has been handled in other PRs so there's nothing left to do.
