### ISSUE TITLE
Add coumentation covering the plugin registry and its governance process

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#634]
## User story

As a user I want to understand how to add plugins to the registry, how to find plugins for my IF workflows and how the plugins are accepted for listing on the site. This understanding will make it easier for me to navigate the IF ecosystem.

## Rationale
We are creating a public registry for IF plugins. We need to make the registry easily discoverable and provide documentation that helps users browse the plugin ecosystem so they can build effective pipelines for their use cases.

## Implementation details
- [ ] add page on if.greensoftware.foundation
- [ ] add links to registry on existing pages on if.greensoftware.foundation
- [ ] add link to registry to readmes for IF repositories

## Priority
4/5

## Size
M

## What does "done" look like?
New page exists, links added to existing pages and readmes.

## Deadline
tbc

**Comment by zanete** [comment]
@ash-ara tagging you on this one so you have a reference to the context regarding that IF plugin wiki page

**Comment by zanete** [comment]
@jawache can you please check this copy https://www.notion.so/grnsft/How-to-add-plugins-104294fed34f46d7ae9e48f2acd164dd to see if you're happy for it to be published? If so, @ash-ara will be adding it to the wiki - and we can direct people to it from the plugin registry

**Comment by zanete** [comment]
@ash-ara please share a link with me when you've added this in the wiki 🙏

**Comment by ash-ara** [comment]
@zanete it's here: https://wiki.greensoftware.foundation/how-to-add-plugins
