### ISSUE TITLE
Add pre-release beta to existing CI/CD to improve release process

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#643]
Sub of: #651   (TBC) 
**What**
Adds pre-release beta to existing CI/CD to remove some friction from our current release process.

**Why**
This will make the release process easier because more will be automated. It will require less manual intervention and fewer steps to manage.

**Context**
We currently maintain three repositories that we release npm packages from. Each repository has its own release process that includes creating a release PR and then manually created and publishing a release on npm. Only then can the release be tested and any bugs have to be hotfixed and a new release created on the fly. This is quite a fragile process and often takes a few hours to coordinate, which can be cut down substantially using some more automation.

**Prerequisites/resources**
None

**Statement of Work**
- [x] define changes to CI/CD that will enable easier releases
- [x] test new flow using a dummy repository
- [x] raise PR updating CI config that implements new process
- [ ] add instructions to github processes doc

**Acceptance criteria**

- [x] tagged release triggers automatic commit to be pushed to `main` that updates package and lock files that include new version numbers
- [x] merging `main` into `release` triggers new release to be created automatically on npm
- [x] release process has the option to create beta releases for testing purposes

**Comment by jmcook1186** [comment]
new process implemented in #649 documented here https://github.com/Green-Software-Foundation/if/pull/662

**Comment by zanete** [comment]
Need to rename the branches from master to Main

**Comment by narekhovhannisyan** [comment]
commit should be presented via PR
