### ISSUE TITLE
Design v1 of the Plugin Registry site

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#661]
Why: sub of #633 
What: Design for MVP of plugin registry

**Scope of work:**
- [x] Spike: What's possible to suck from npm (e.g. downloads, stars etc)
- [x] Design and link to figma
- - [x] Place for disclaimer (copy tbc)
- - [x] Header with links to IF and "How to submit a plugin"
- - [x] Search box
- - [x] A plugin card - [Name of the plugin, summary (one sentence), Tags, URLs(npm, repo or website), badge for official plugins, version,  stats tbc
- [x] Review and feedback on the design
- [ ] Provide a sample json file to show the format in which data should be prepared (for #685 )

**Comment by zanete** [comment]
FYI @osamajandali apparently, according to @narekhovhannisyan , https://github.com/NodeSecure/npm-registry-sdk will give you all the stats. This is in reference to the first AC on this issue.

**Comment by zanete** [comment]
@jmcook1186 here's a good place for you to let @osamajandali know about the repo you created #614 :)

**Comment by jmcook1186** [comment]
hi @osamajandali  - just to let you know this repo exists and should be the home for plugin registry website source code eventually.
https://github.com/Green-Software-Foundation/if-plugin-website

**Comment by zanete** [comment]
Capturing the status in the weekly call: this is yet to be started as @osamajandali was delayed in returning from his vacation

**Comment by osamajandali** [comment]
@zanete Here is the design:
https://www.figma.com/proto/kFxZ110Mo2n5O8kuwAH8nk/GSF---Plugin-Register?page-id=1%3A2076&type=design&node-id=1-2805&viewport=471%2C687%2C0.18&t=GRZ4eMkI4USSiDu0-1&scaling=scale-down-width&mode=design

**Comment by zanete** [comment]
@jawache @jmcook1186 (cc @osamajandali ) I love the design, and all is super cool, only unclear if the "official plugin" badge should be as explicitly stating that it's an official plugin or something more subtle to show endorsement that would also allow highlighting external plugins?  
Regardless, feels like we're good to go with the next stage that is preparing the json structure so that we can prepare data (and move on with implementation as part of #684)

**Comment by jmcook1186** [comment]
Love the design - really no criticism of how the page looks at all.

I will have some comments about the content of the cards - we haven't provided any guidance on that so far, but I anticipate each card containing:

- plugin name
- publisher name
- short description of the plugin
- link to npm/github
- link to issue form that was filled out when PR to add plugin was raised
- a badge (which probably will not contain the text `GSF official plugin` (this might not exist on launch, but we will want to add badges later)

**Comment by zanete** [comment]
@jmcook1186 noted, we've seen that we are missing publisher name which we'll add. 
Can we clarify why we need `link to issue form that was filled out when PR to add plugin was raised `on this website? is this something that the public should have access to?

**Comment by jmcook1186** [comment]
Yes- this still needs to be confirmed with @jawache but I'm anticipating that users will be able to raise PRs against the registry repository to add plugins to the site. When they do so, they will have to fill out a simple issue form that asks them some basic questions about their plugin:

- what does your plugin do?
- what are the parameters and return values?
- have you provided a README with usage instructions
- have you provided a working manifest file that invoked your plugin
- have your provided unit tests covering your plugin
- please provide citations or other supporting material that can be used to assess your plugin
etc

We want to be able to click from the card on the site to the author's responses on the issue form as a shortcut for the community to do their own due diligence before installing the plugins.

**Comment by jawache** [comment]
Hey so @jmcook1186 I was thinking for this MVP we match the functionality of the gulp registry.

Each card is linked to one place, either the npm or GitHub if there is no npm link.

Its a good idea to insist the plugins report some common info, but I'd argue they have to list that clearly on the plugin landing page in npm/gh, rather than document it in the PR itself. We can just check their npm landing page to make sure it's.there as we expect.

I'm also ok with the process of submitting being that they edit the JSON file that powers the registry, add their info, have PR check boxes like you say but the actual answers should be on their plugin landing page. We review to make sure they match our requirements, then all we have to do is accept the PR and it will be added to the registry.

**Comment by jmcook1186** [comment]
sure - I just want a user to be able to tell at a glance whether a plugin meets our basic set of requirements. The form can literally just be a set of checkboxes with the actual information being in the GH repo or npm page.

I also anticipated a PR being a new entry to the json file.

**Comment by jawache** [comment]
In that case not sure if there is a ticket for this, but as well as the plugin registry we'll also need some docs to explain the process and minimum requirements for the plugin (docs/landing page etc...)

To make life easier we can add it to if-docs, or create a page in our Notion wiki, whatever is easiest.

**Comment by zanete** [comment]
@jawache - we have #634 for documenting etc. In the design there are multiple links supported, so we can add all links that are needed.
@jmcook1186 I get why we would want extra info to accommodate the PR submission internally, I but I'm not sure I follow why that is needed for the wider public. Shouldn't we encourage them to put all publicly relevant info in their readmes?

**Comment by zanete** [comment]
Json referred to the other task #684
