### ISSUE TITLE
Move `multiply` to `if/builtins`

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#679]
Sub of: #656

**What**
Move the `multiply` plugin from `if-plugins` to `if/builtins`

**Why**
This is part of our migration of our core plugins into a standard library in `if/builtins`.

**Context**
This is a core feature we want to support, so it is migrating into `if`. 

**Prerequisites/resources**
no

**SoW (scope of work)**
- [ ] move plugin code into `builtins/multiply`
- [ ] fix any integration issues caused by the migration
- [ ] migrate and fix unit tests 
- [ ] update README documentation updated

**Acceptance criteria**
- [ ] plugin code is migrated to `if-builtins`
**Given** (Setup): The migration has been completed.
**When** (Action): A user or developer navigates to `if`
**Then** (Assertion): they will find a folder `if/builtins/multiply` containing the plugin source code and a README.

- [ ] plugin code and unit tests pass and maintain 100% coverage
**Given** (Setup): The migration has been completed and a user has downloaded `if`.
**When** (Action): they run `npx jest --coverage`
**Then** (Assertion): they will receive a report showing 100% coverage and 100% passing
