### ISSUE TITLE
Move `tdp-finder` csvs to its own repo

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#728]
**Why**: Sub of #546 

**What**: Move the tdp-finder to its own repo

**context**
We are migrating plugins out of `if-unofficial-plugins` in order to deprecate that repository. The tdp finder can be replaced with the new csv-lookup plugin, but the csvs still need to be hosted somewhere. In the absence of a willing external host, we can keep them but move them into a new repository.

**Scope of work:**
 - [x] create new repo in GSF org
 - [x] copy tdp-finder CSV files into repo
 - [x] copy files from cloud instance metadata
 - [x] copy files from cloud region metadata

**prerequisites**

This is blocked on the development of the CSV lookup plugin #674 

**Acceptance criteria:**
- [x] There is a repository in the GSF organization called `if-data` that contains the csv files that are currently supporting the tdp-finder, region metadata and instance metadata plugins

**Comment by zanete** [comment]
@jmcook1186 please see this one and update AC and SoW as needed 🙏

**Comment by zanete** [comment]
On behalf of @jawache the RTC data be added to the same repo and the repo should be called `if-data`

**Comment by jmcook1186** [comment]
moved csvs from tdp-finder, region-metadata and instance metadata to gsf/if-data
