### ISSUE TITLE
Audit import paths for all manifests in `if`

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#740]
**What** 

Check through all existing manifests and ensure that the import paths for plugins are correct. This especially applies to plugins that have recently been moved from `if-plugins` to `builtins` as there may be some trailing `path: @gtnsft/if-plugins` that need to be updated.

**Why**

To ensure all our example manifests execute correctly.

**SoW**

- [ ] check through all existing manifests and identify cases where the import path is incorrect
- [ ] raise a single PR fixing all instances of incorrect import path 

**Acceptance criteria**
- [ ] all import paths are correct
  - GIVEN the audit is complete
    WHEN I execute all the manifests that come bundled with IF
    THEN every manifest executes correctly OR fails in the expected way.

**Comment by zanete** [comment]
@jmcook1186 confirm if this is needed and assign to @MariamKhalatova if it is

**Comment by zanete** [comment]
a PR expected in a few hours 🙏

**Comment by MariamKhalatova** [comment]
> a PR expected in a few hours 🙏

@zanete PR is already provided. Waiting for it to be reviewed
